FROM debian:latest
LABEL maintainer Leandro Moreira <leandro@leandromoreirati.com.br>

COPY configs/   /tmp/configs/

RUN dpkg -i /tmp/configs//zabbix-release_3.4-1+stretch_all.deb && \
    cat /usr/share/doc/apt/examples/sources.list > /etc/apt/sources.list && \
    echo "deb http://ftp.de.debian.org/debian stretch main non-free" >> /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get dist-upgrade -y && \
    apt-get install --no-install-recommends zabbix-frontend-php php7.0-curl php7.0-mcrypt php7.0-pgsql php7.0-soap php7.0-xml php7.0 php7.0-ldap unzip wget locales -y snmp snmp-mibs-downloader && \
    mv -v /tmp/configs/setup.sh /usr/bin/ && \
    mv -v /tmp/configs/zabbix.conf.php /etc/zabbix/web/ && \
    mv -v /tmp/configs/site.conf /etc/apache2/sites-available/ && \
    mv -v /tmp/configs/apache2.conf /etc/apache2/ && \
    mv -v /tmp/configs/php.ini /etc/php/7.0/apache2/ && \
    mv -v /tmp/configs/ports.conf /etc/apache2/ports.conf && \
    rm /etc/localtime && \
    ln -s /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
    sed -i -e 's/# pt_BR.UTF-8 UTF-8/pt_BR.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen pt_BR.UTF-8 && \
    update-locale LANG=pt_BR.UTF-8 && \
    apt-get purge -y unzip wget && \
    apt-get clean && \
    rm -rf /var/www/html/index.html && \ 
    rm -rf /etc/apache2/sites-enabled/* && \ 
    rm -rf /var/lib/apt/lists/* 

ENV LANG='pt_BR.UTF-8'

WORKDIR /etc/apache2

VOLUME /etc/zabbix

VOLUME /usr/share/zabbix

EXPOSE 80

EXPOSE 443

#USER www-data

#ENTRYPOINT [ "setup.sh" ]
